### ISSUE TITLE
Uncaught RPC error [Error: unable to find method 'invoke'] { name: undefined }

### ISSUE THREAD

**Issue by qn0x** [ChiChou/Grapefruit#17]
Hi, after using Passionfruit for a while I wanted to give Grapefruit a try. After installing and choosing an app I get the following error in the GUI (it doesn't matter which app I choose, this error is always shown):  
![image](https://user-images.githubusercontent.com/19463555/97868898-ccf19a00-1d10-11eb-91a9-e0c14f2543c0.png)

The corresponding terminal output:
![image](https://user-images.githubusercontent.com/19463555/97869079-1e9a2480-1d11-11eb-9e97-6a5e3f734155.png)

**Environment:**
Node version: v14.15.0
Frida version: 14.0.1
iOS Frida version: 14.0.5

Any idea why this could be happening?

**Comment by ChiChou** [comment]
It's a bug. Thanks for reporting
