### ISSUE TITLE
Server crashes on node.js > v14

### ISSUE THREAD

**Issue by 0x023** [ChiChou/Grapefruit#20]
Using iOS with frida 14.08 , selecting an app in the web application triggers a proxy error:
Running Ubuntu 18.04 with nodejs 14

Proxy error: Could not proxy request /socket.io/?EIO=3&transport=websocket from 192.168.1.49:8081 to http://localhost:31337/.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

Proxy error: Could not proxy request /socket.io/?EIO=3&transport=websocket from 192.168.1.49:8081 to http://localhost:31337/.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

Proxy error: Could not proxy request /api/remote/add from 192.168.1.49:8081 to http://localhost:31337/.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

Please advise.

**Comment by ChiChou** [comment]
This means that the server has crashed. I've noticed the problem and it seemed to be related to WebSocket.
Still trying to figure it out.

A temporary workaround is to restart the server. You can either:

1. <kbd>Ctrl - C</kbd> to close all tmux panels and run `npm start` again
2. Add a comment or any code with no side effects to the `server/app.ts` , save it to trigger the autoreload, and `nodemon` wil reload the server side

The second workaround is faster but you have to make sure that your changes won't break the server

**Comment by ChiChou** [comment]
I've pushed a workaround for this to avoid accessing the icon of the devices.
