### ISSUE TITLE
can 't connect to local app because of losing the state of jailbreak. ops

### ISSUE THREAD

**Issue by todayios-cydia** [ChiChou/grapefruit#29]
can 't connect to local app . the app stuck on launch screen

**Comment by ChiChou** [comment]
Can you check the terminal output

**Comment by todayios-cydia** [comment]
[log.txt](https://github.com/ChiChou/grapefruit/files/6225723/log.txt)
That's the log file . 
Its seems everything is ok . that's wired. 

The app i want to check is stucking on the launch screen after i click the icon on the list of grapefruit.

Env:
iOS 14.2
FRIDA VERSION: 14.2.14
node --version
v10.20.1

**Comment by todayios-cydia** [comment]
i have tried another device and i works.

**Comment by todayios-cydia** [comment]
sorry!  that's not the issue
