### ISSUE TITLE
A14设备使用后无法打开app

### ISSUE THREAD

**Issue by zwsn** [ChiChou/grapefruit#30]
iPhone 12 Pro 系统14.1，使用数据线链接，Frida版本14.2.13，使用后打开应用始终卡在启动界面。

**Comment by ChiChou** [comment]
先手机上运行 app，即可切换为 attach 模式

**Comment by zwsn** [comment]
查看已经运行的应用grapefruit始终卡在加载动画中
![image](https://user-images.githubusercontent.com/42889307/113085569-b04f8480-9212-11eb-9df9-cf6637ecec00.png)

**Comment by zwsn** [comment]
> 查看已经运行的应用grapefruit始终卡在加载动画中
> ![图像](https://user-images.githubusercontent.com/42889307/113085569-b04f8480-9212-11eb-9df9-cf6637ecec00.png)

已解决，iOS上安装的frida版本问题，换成最新版就可以了
