### ISSUE TITLE
Cannot open application in Grapefruit

### ISSUE THREAD

**Issue by sytnikv** [ChiChou/grapefruit#31]
Using igf from npm. Upon start Grapefruit sees iphone, successfully lists installed apps, but when I select the application and try to open it in Grapefruit - it doesn't load.

Terminal output:
`  Error: read ECONNRESET
      at TCP.onStreamRead (internal/stream_base_commons.js:209:20)

(node:51662) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/igf/agent/dist.js'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:51662) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:51662) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

I checked, dist.js file is missing on the filesystem and it's not present in the repo.

**Comment by ChiChou** [comment]
Thanks for reporting. This is due to an error in packaging. Patched in v0.8.6
