### ISSUE TITLE
Hi ChiChou,

### ISSUE THREAD

**Issue by ahmedx90T** [ChiChou/grapefruit#33]
Hi ChiChou,

The issue got resolved, it was some nodejs error. It works fine.
Thank you :)

One query: Is it always better to run the production build for testing? or is the development build have any restrictions in place at present?

_Originally posted by @hehacks in https://github.com/ChiChou/grapefruit/issues/5#issuecomment-656302412_

**Comment by ahmedx90T** [comment]
what is the steps that you used to solve the problem , i have the same issue ?

**Comment by ChiChou** [comment]
Please describe the bug clearly
