### ISSUE TITLE
disasm.vue -> Object is possibly 'undefined'

### ISSUE THREAD

**Issue by uBadRequest** [ChiChou/Grapefruit#4]
Getting an error "Object is possibly undefined. First time run and latest build.
-> this.disam.pop()

https://github.com/ChiChou/Grapefruit/blob/5eb31e6f597808cfce59748bfb21793cd4b3d315/gui/src/views/tabs/Disasm.vue#L102

**Comment by ChiChou** [comment]
It's a TypeScript bug. When `disasm.length >1` it won't be undefined
