### ISSUE TITLE
IGF stuck at device fetch information page

### ISSUE THREAD

**Issue by B4RD4k** [ChiChou/grapefruit#45]
Hi, 

I am using Iphone SE 13.3 jailbroken and installed with frida 15.0.2 (installed from cydia repo).
I tried to install igf using npm install -g igf and it was installed without errors.
now it stuck at the page described above (ss attached)

any help?
10x

![image](https://user-images.githubusercontent.com/7777720/125158348-47fd3100-e179-11eb-81df-59aca9df450f.png)

**Comment by B4RD4k** [comment]
I just checked the frida version installed with python and it's working on 15.0.2. 
changing the package.json to frida 15.0.2 returned a lot of errors during the installation process.

**Comment by B4RD4k** [comment]
Update: 
Looks like IGF doesn't suupport frida-node >= 15.0.0.

![image](https://user-images.githubusercontent.com/7777720/125159381-bba23c80-e17f-11eb-9dd6-bc6c48e71a95.png)

**Comment by ChiChou** [comment]
Try v0.9.2

**Comment by B4RD4k** [comment]
Works thanks for the hard work!
