### ISSUE TITLE
Proxy error: Could not proxy request (HPE_INVALID_CONSTANT).

### ISSUE THREAD

**Issue by hehacks** [ChiChou/Grapefruit#5]
Hi Team,

I am getting the below shown error while trying to connect my device.

Proxy error: Could not proxy request /api/devices from localhost:8080 to http://localhost:31337/ (HPE_INVALID_CONSTANT).

Note: Jailbroken iphone connected via USB.
The grapefruit is installed and is up and running on the below IPs;

App running at:
  - Local:   http://localhost:8080/
  - Network: http://192.168.0.132:8080/

Can you help me with some hints on how to proxy my localhost:8080 (my mac machine) to http://localhost:31337/  (jailbroken iphone)?

**Comment by ChiChou** [comment]
It seems like a server side error. Please attach the console logs

**Comment by hehacks** [comment]
I have got the below error while checking in the console
` DONE  Compiled successfully in 13191ms                                                                                                                                                                                            11:01:14 PM

No type errors found
Version: typescript 3.7.5
Time: 4245ms

  App running at:
  - Local:   http://localhost:8080/
  - Network: http://192.168.0.132:8080/

  Note that the development build is not optimized.
  To create a production build, run npm run build.

Proxy error: Could not proxy request /socket.io/?EIO=3&transport=websocket from localhost:8080 to http://localhost:31337/.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

Proxy error: Could not proxy request /api/devices from localhost:8080 to http://localhost:31337/.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

Proxy error: Could not proxy request /socket.io/?EIO=3&transport=websocket from localhost:8080 to http://localhost:31337/.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

Proxy error: Could not proxy request /socket.io/?EIO=3&transport=websocket from localhost:8080 to http://localhost:31337/.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

Proxy error: Could not proxy request /socket.io/?EIO=3&transport=websocket from localhost:8080 to http://localhost:31337/.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

Proxy error: Could not proxy request /socket.io/?EIO=3&transport=websocket from localhost:8080 to http://localhost:31337/.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

Proxy error: Could not proxy request /socket.io/?EIO=3&transport=websocket from localhost:8080 to http://localhost:31337/.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

Proxy error: Could not proxy request /socket.io/?EIO=3&transport=websocket from localhost:8080 to http://localhost:31337/.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

Proxy error: Could not proxy request /socket.io/?EIO=3&transport=websocket from localhost:8080 to http://localhost:31337/.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

Proxy error: Could not proxy request /socket.io/?EIO=3&transport=websocket from localhost:8080 to http://localhost:31337/.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

Proxy error: Could not proxy request /socket.io/?EIO=3&transport=websocket from localhost:8080 to http://localhost:31337/.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

Proxy error: Could not proxy request /socket.io/?EIO=3&transport=websocket from localhost:8080 to http://localhost:31337/.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

Proxy error: Could not proxy request /api/remote/add from localhost:8080 to http://localhost:31337/.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

Proxy error: Could not proxy request /socket.io/?EIO=3&transport=websocket from localhost:8080 to http://localhost:31337/.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

Proxy error: Could not proxy request /api/remote/add from localhost:8080 to http://localhost:31337/.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

Proxy error: Could not proxy request /api/remote/add from localhost:8080 to http://localhost:31337/.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

Proxy error: Could not proxy request /socket.io/?EIO=3&transport=websocket from localhost:8080 to http://localhost:31337/.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

Proxy error: Could not proxy request /socket.io/?EIO=3&transport=websocket from localhost:8080 to http://localhost:31337/.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

Proxy error: Could not proxy request /socket.io/?EIO=3&transport=websocket from localhost:8080 to http://localhost:31337/.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).`

**Comment by ChiChou** [comment]
There are three tabs. This one is the WebPack and it does not provide the right information.

You need to find the one like this:

```
> grapefruit-server@0.7.0 dev H:\Grapefruit\server
> nodemon

[nodemon] 2.0.2
```

**Comment by hehacks** [comment]
Hi ChiChou,

The issue got resolved, it was some nodejs error. It works fine.
Thank you :)

One query: Is it always better to run the production build for testing? or is the development build have any restrictions in place at present?

**Comment by ChiChou** [comment]
It's not recommended to use the current codebase since it's in progress and unstable. Please wait for the Beta release, though I can't guarantee the timetable

**Comment by ChiChou** [comment]
So the production build is avaliable now. Please do not use the development environment unless you know exactly what you're doing
