### ISSUE TITLE
"Connecting" forever

### ISSUE THREAD

**Issue by yindeming** [ChiChou/grapefruit#52]
UPDATE: Aftrer reboot Mac and reconnect iPhone, the issue is gone, please close, thanks.

I have lastest frida 15.1.18 on iphone SE (iOS version 13.7) and Mac OS. 

After install grape fruit with npm, I'm able to find iPhone from 127.0.0.1:31337 and connect.

But when I try to connect to my app, it won't connect, just saying Connecting. Thanks.

**Comment by ChiChou** [comment]
Does refreshing the page work

**Comment by yindeming** [comment]
Thank you. Refresh page doesn't work, but I don't think it's a grapefruite issue, as other software could not connect iphone at that time.
