### ISSUE TITLE
Startup Script

### ISSUE THREAD

**Issue by madt1m** [ChiChou/grapefruit#64]
Hello, and thanks for this great project, the interface is really snappy and with lots of functionality!

So, I am currently dealing with an app that has jailbreak detection, and I'd like to load a script as soon as the app starts. Is there a way to do so in Grapefruit? If so, I'm sorry for not finding it!

**Comment by madt1m** [comment]
Update: I think I have found a working approach. By injecting my startup script and spawning the app with frida, it seems that Grapefruit will then attach to the already running process, so that the goal is reached! @ChiChou if you can confirm that this is the suggested approach, I think the issue can be closed.

**Comment by ChiChou** [comment]
Yes this is by design. Frida supports multiple sessions on one process by natural. If an app is already running, we will attach it instead of spawning a new one
