### ISSUE TITLE
 ERROR  Failed to compile with 1 error-  while running the npm 

### ISSUE THREAD

**Issue by sidh104** [ChiChou/Grapefruit#7]
![image](https://user-images.githubusercontent.com/25565541/87394088-db367180-c5cc-11ea-880a-6efb7810a1df.png)

**Comment by ChiChou** [comment]
You've missed `--recurse-submodules` flag in `git clone`, which is already documented.

`git submodule init && git submodule update` to resolve this

**Comment by sidh104** [comment]
cloned using.... git clone --recurse-submodules https://github.com/ChiChou/Grapefruit

also did run git submodule update --init

but receiving this error: fatal: not a git repository (or any of the parent directories): .git

**Comment by ChiChou** [comment]
You are running the command in a wrong directory.

`git submodule update --init` needs to be used in the root directory of your local Grapefruit copy, and **that's all you need to fix the problem**.

`git clone --recurse-submodules https://github.com/ChiChou/Grapefruit.git` means cloning the whole repo again from the scrach.

You need to learn more about git
https://git-scm.com/docs/gittutorial

And please do not open new issue for the same question. Use **reopen** if you think it's not resolved.

**Comment by ChiChou** [comment]
Here is the [Discord channel](https://discord.gg/pwutZNx) of the project. You may get quicker response here

**Comment by sidh104** [comment]
Thanks for the quick response and Knowledge transfer appreciate it, Thanks alot :)
