### ISSUE TITLE
Warning - local regulation restrictions

### ISSUE THREAD

**Issue by novitae** [ChiChou/grapefruit#83]
Hello,
I am currently having this issue:
When spawning on my Unc0ver jailbroken iPhone 6 the app `抖音` (douyin, the Chinese TikTok), here's what happens:

<img width="819" alt="Capture d’écran 2022-12-03 à 23 16 03" src="https://user-images.githubusercontent.com/85891169/205464272-a6b7cb5c-09e1-4b0c-a63f-75d8014cee1b.png">

Is it coming from the app, which is known for its crazy security measures, or from igf ? Thanks

**Comment by ChiChou** [comment]
https://github.com/ChiChou/grapefruit/blob/f4e9fd3e4411a04d8a8e90453acb8e9ea270c19a/gui/src/regulation.ts#L3

This is by design, as some Chinese vendors sued people for reverse engineering or dynamic patching on their apps.

**Comment by novitae** [comment]
Thanks !
