### ISSUE TITLE
npm run dev fails using Node 17+

### ISSUE THREAD

**Issue by jpstotz** [ChiChou/grapefruit#85]
Cloning the grapefruit GIT repo following https://github.com/ChiChou/grapefruit/wiki/Development-Setup starting the development server fails:

```
Grapefruit-git\gui\src\main.tsError: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    ...
```

It seems like the used webpack version and it's configuration is not compatible with Node 17+.

I tried to change webpack configuration to `output.hashFunction = 'sha256'` as mentioned in https://stackoverflow.com/a/73027407/150978, however I am not familiar with webpack in TypeScript projects so I don't know where to put that configuration.

**Comment by ChiChou** [comment]
The active developing branch is https://github.com/ChiChou/grapefruit/tree/vue3
That branch is a rewrite so nothing works yet. However it's not affected by this issue

**Comment by jpstotz** [comment]
@ChiChou Thanks for your feedback. For me this is good and bad news at the same time, because there is now one branch I could make changes to (like attaching to a non-app process, list superClass, argumentTypes, ...), but it doesn't build and it is a dead end so the changes would be lost.
And the new branch with the rewrite which could in general be built but misses all the functionality.

Nevertheless thank you for Grapefruit.
