### ISSUE TITLE
How to use hook 

### ISSUE THREAD

**Issue by Chensem** [ChiChou/grapefruit#86]
I found some hook code in your project , but i can't see any reference 
![image](https://user-images.githubusercontent.com/27469499/218366242-a33c540f-e10d-46a3-9df4-a3a7cc87adde.png)
so this hooks how to use ? and why retain in your project .

**Comment by ChiChou** [comment]
I've planned many features but the project development is going very slow

**Comment by ienthach** [comment]
> I've planned many features but the project development is going very slow

could grapefruit inject to other processes like daemon.

**Comment by ChiChou** [comment]
> > I've planned many features but the project development is going very slow
> 
> 
> 
> could grapefruit inject to other processes like daemon.

But it doesn't make sense to inject daemon. Most of the features are designed for apps

**Comment by ienthach** [comment]
> But it doesn't make sense to inject daemon. Most of the features are designed for apps

Thank you, this project is very powerful with for works. Maybe in other project you can support it.

**Comment by ChiChou** [comment]
> > But it doesn't make sense to inject daemon. Most of the features are designed for apps
> 
> Thank you, this project is very powerful with for works. Maybe in other project you can support it.

Try this maybe?

* https://marketplace.visualstudio.com/items?itemName=CodeColorist.vscode-frida
* https://github.com/ChiChou/vscode-frida
