### ISSUE TITLE
Download file failed

### ISSUE THREAD

**Issue by Chensem** [ChiChou/grapefruit#88]
**Describe the bug**
Download any file in Folder Tree 
![image](https://user-images.githubusercontent.com/27469499/223983186-9478f578-b319-4beb-907b-954705b4cede.png)
Then send a request to server
![image](https://user-images.githubusercontent.com/27469499/223983271-a9d3f109-5670-4201-8a8c-19d5094a7207.png)
server loggs show when click download , script destoryed , so download file failed 
![image](https://user-images.githubusercontent.com/27469499/223983498-0c4811e4-c1ca-4aa5-92a5-c360eee015ac.png)

**Comment by Chensem** [comment]
replace with window.open

**Comment by ChiChou** [comment]
frida-fs 的 bug
https://github.com/frida/frida/issues/2447
