### ISSUE TITLE
Uncaught RPC error [Error: unable to find method 'invoke']

### ISSUE THREAD

**Issue by danweber** [ChiChou/grapefruit#91]
**Describe the bug**

Uncaught RPC error [Error: unable to find method 'invoke'] { name: undefined }
method: info/info args: []
Uncaught RPC error [Error: unable to find method 'invoke'] { name: undefined }
method: cookies/list args: []
Uncaught RPC error [Error: unable to find method 'invoke'] { name: undefined }
method: scanner/privacy args: []
Uncaught RPC error [Error: unable to find method 'invoke'] { name: undefined }
method: checksec args: []

**To Reproduce**

1. Connect my physical rooted Pixel to my computer.
2. Launch igf and then click on my Pixel.
3. From the list of apps, click any of them

**Desktop (please complete the following information):**
 - OS: MacOS 13.3.1 (a) 
 - Browser: Chrome
 - NODEJS: V19.9.0;
 - NODE-FRIDA: 16.1.2

**Phone (please complete the following information):**
 - Device: Pixel 6a
 - OS: TQ3A.230705.001
 - Rooted
 - Frida Version: `bluejay:/data/local/tmp # ./frida-server-16.1.2-android-arm64` 

**Additional context**
 - I ran in a virtual node environment because my system already had a Node@20 installed. Frida otherwise works.

**Comment by ChiChou** [comment]
??????
